param(
    [Parameter(Mandatory = $true)]
    [string]$Server,

    [Parameter(Mandatory = $true)]
    [string]$Token,

    [string]$SystemName = $env:COMPUTERNAME,

    [int]$IntervalSeconds = 60
)

$ErrorActionPreference = "Stop"
$Server = $Server.TrimEnd("/")
$InstallPath = "C:\ProgramData\Orion\SysPulse"
$ConfigPath = Join-Path $InstallPath "config.json"
$AgentPath = Join-Path $InstallPath "agent.ps1"
$TaskName = "Orion SysPulse Agent"

New-Item -ItemType Directory -Path $InstallPath -Force | Out-Null

# 1. Automatically fetch token and config from the server for this specific computer
Write-Host "[1/5] Registering agent and downloading configuration for '$SystemName'..."
try {
    $TokenUrl = "$Server/api/v1/token?system=$SystemName"
    $TokenResponse = Invoke-RestMethod -Uri $TokenUrl -Method Get
    
    # Download the full config.json generated by the server
    $ConfigUrl = "$Server/api/v1/config/$SystemName"
    Invoke-WebRequest -Uri $ConfigUrl -OutFile $ConfigPath -UseBasicParsing
    Write-Host "Successfully registered and downloaded config from server." -ForegroundColor Green
}
catch {
    Write-Warning "Could not auto-register with server. Using fallback local configuration..."
    # Fallback default configuration if registration fails
    $FallbackConfig = @{
        agent = @{ name = $SystemName; version = "1.0.0"; intervalSeconds = 60 }
        collector = @{ endpoint = "$Server/api/v1/telemetry"; token = "fallback-token" }
        collectors = @{ system=$true; cpu=$true; memory=$true; disk=$true; network=$true; processes=$true; services=$true; applications=$true; updates=$true; users=$true; uptime=$true }
    } | ConvertTo-Json -Depth 10
    Set-Content -Path $ConfigPath -Value $FallbackConfig
}

# 2. Download Agent Script
Write-Host "[2/5] Downloading Windows agent..."
$ZipUrl ="https://github.com/GopiraviG/orion-agent-windows/releases/download/v1.0.0/orion-agent-win.zip"

$tempZip ="$env:TEMP\orion-agent-win.zip"

Invoke-WebRequest `-Uri $ZipUrl `-OutFile $tempZip

Expand-Archive `
    -Path $tempZip `
    -DestinationPath $InstallPath `
    -Force
``
#Invoke-WebRequest -Uri "$Server/agent/windows/agent-windows.ps1" -OutFile $AgentPath -UseBasicParsing
# ============================================================
# CONFIGURATION (DYNAMIC FROM SERVER WITH FALLBACK)
# ============================================================

Write-Host "[3/5] Downloading/Creating configuration for '$SystemName'..."

$ConfigUrl = "$Server/api/v1/config/$SystemName"
$ConfigDownloaded = $false

try {
    Invoke-WebRequest -Uri $ConfigUrl -OutFile $ConfigPath -UseBasicParsing
    if (Test-Path $ConfigPath) {
        Write-Host "Configuration downloaded successfully from server." -ForegroundColor Green
        $ConfigDownloaded = $true
    }
}
catch {
    Write-Warning "Could not download remote config. Generating fallback configuration..."
}

if (-not $ConfigDownloaded) {
    $config = @{
        agent = @{
            name = $SystemName
            version = "1.0.0"
            intervalSeconds = $IntervalSeconds
        }

        collector = @{
            endpoint = "$Server/api/v1/telemetry"
            token = $Token
        }

        collectors = @{
            system       = $true
            cpu          = $true
            memory       = $true
            disk         = $true
            network      = $true
            processes    = $true
            services     = $true
            applications = $true
            updates      = $true
            users        = $true
            uptime       = $true
        }
    }

    $config |
        ConvertTo-Json -Depth 20 |
        Set-Content `
            -Path $ConfigPath `
            -Encoding UTF8

    Write-Host "Fallback configuration created."
}

# ============================================================
# STOP / REMOVE OLD TASK
# ============================================================

Write-Host "[4/5] Replacing existing agent task..."

try {
    Stop-ScheduledTask `
        -TaskName $TaskName `
        -ErrorAction SilentlyContinue
}
catch {
}

try {
    Unregister-ScheduledTask `
        -TaskName $TaskName `
        -Confirm:$false `
        -ErrorAction SilentlyContinue
}
catch {
}

# ============================================================
# TEST TELEMETRY
# ============================================================

Write-Host ""
Write-Host "Testing telemetry..."

try {
    & powershell.exe `
        -NoProfile `
        -NonInteractive `
        -ExecutionPolicy Bypass `
        -File $AgentPath `
        --once

    if ($LASTEXITCODE -eq 0) {
        Write-Host ""
        Write-Host `
            "Telemetry test successful." `
            -ForegroundColor Green
    }
    else {
        Write-Host ""
        Write-Host `
            "Telemetry test failed with exit code $LASTEXITCODE" `
            -ForegroundColor Yellow
    }
}
catch {
    Write-Host ""
    Write-Host `
        "Telemetry test failed: $($_.Exception.Message)" `
        -ForegroundColor Yellow
}

# ============================================================
# SCHEDULED TASK
# ============================================================

Write-Host ""
Write-Host "Registering automatic agent..."

$PowerShellExe =
    "$env:SystemRoot\System32\WindowsPowerShell\v1.0\powershell.exe"

$Arguments =
    "-NoProfile -NonInteractive -ExecutionPolicy Bypass -File `"$AgentPath`""

$Action =
    New-ScheduledTaskAction `
        -Execute $PowerShellExe `
        -Argument $Arguments `
        -WorkingDirectory $InstallPath

$TriggerStartup =
    New-ScheduledTaskTrigger `
        -AtStartup

$TriggerOnce =
    New-ScheduledTaskTrigger `
        -Once `
        -At (Get-Date).AddSeconds(5)

$Principal =
    New-ScheduledTaskPrincipal `
        -UserId "SYSTEM" `
        -LogonType ServiceAccount `
        -RunLevel Highest

$Settings =
    New-ScheduledTaskSettingsSet `
        -AllowStartIfOnBatteries `
        -DontStopIfGoingOnBatteries `
        -StartWhenAvailable `
        -ExecutionTimeLimit (
            [TimeSpan]::Zero
        ) `
        -RestartCount 10 `
        -RestartInterval (
            New-TimeSpan -Minutes 1
        )

$Task =
    New-ScheduledTask `
        -Action $Action `
        -Trigger @(
            $TriggerStartup,$TriggerOnce
        ) `
        -Principal $Principal `
        -Settings $Settings `
        -Description `
            "Orion SysPulse continuous Windows telemetry agent"

Register-ScheduledTask `
    -TaskName $TaskName `
    -InputObject $Task `
    -Force |
    Out-Null

# ============================================================
# START IMMEDIATELY
# ============================================================

Write-Host "Starting agent..."

Start-ScheduledTask `
    -TaskName $TaskName

Start-Sleep `
    -Seconds 3

# ============================================================
# VERIFY
# ============================================================

$TaskInfo =
    Get-ScheduledTask `
        -TaskName $TaskName

Write-Host ""
Write-Host "==================================================" -ForegroundColor Green
Write-Host "       Orion SysPulse Agent Installed" -ForegroundColor Green
Write-Host "==================================================" -ForegroundColor Green
Write-Host ""

Write-Host "Agent  : $AgentPath"
Write-Host "Config : $ConfigPath"
Write-Host "Log    : $LogPath"
Write-Host "Task   : $TaskName"
Write-Host ""

Write-Host "Collector:"
Write-Host "  $Server/api/v1/telemetry"
Write-Host ""

Write-Host "Interval:"
Write-Host "  $IntervalSeconds seconds"
Write-Host ""

Write-Host "Task state:"
Write-Host "  $($TaskInfo.State)" -ForegroundColor Green

Write-Host ""
Write-Host "Agent is running automatically." -ForegroundColor Green
Write-Host "You do NOT need to run agent.ps1 manually." -ForegroundColor Green
Write-Host ""